#!/usr/bin/python3 -u

import argparse
import sys

import requests_unixsocket
import yaml


# parent (abstract) class for all lxd resources
class Resource:
    def __init__(self, collection_url, name):
        # relative api url for this type of lxd resource (for example: "/1.0/containers")
        self._collection_url = collection_url
        # the name of this specific resource
        self._name = name

    # returns the full api url for this type of lxd resource
    def get_full_collection_url(self):
        return api_url + self._collection_url

    # returns the full api url for this specific resource
    def get_full_element_url(self):
        return self.get_full_collection_url() + "/" + self._name

    # returns whether this specific resource exists or not...
    def exists(self):
        # by checking if the resource's name is listed in the response of the collection url
        return any(filter(
            lambda a: a == self._collection_url + "/" + self._name,
            session.get(self.get_full_collection_url()).json().get("metadata")
        ))

    # meant to be called by actual "create" functions in child classes with a json template matching the resource's type
    # handles the basic api resource creation
    def _create(self, json):
        # only does something if the resource doesn't already exist (idempotence)
        if not self.exists():
            print("creating", self._collection_url, self._name)
            session.post(self.get_full_collection_url(), json=json)
            if not self.exists():
                raise Exception("resource creation failed")

    # deletes this specific resource
    def delete(self):
        # only does something if the resource exists (idempotence)
        if self.exists():
            print("deleting", self._collection_url, self._name)
            session.delete(self.get_full_element_url())
            if self.exists():
                raise Exception("resource deletion failed")


class Network(Resource):
    def __init__(self, network_config):
        super().__init__("/1.0/networks", network_config.get("name"))

        # additional attributes
        self._network_config = network_config

    def create(self):
        super()._create(self._network_config)


class Profile(Resource):
    def __init__(self, profile_config):
        super().__init__("/1.0/profiles", profile_config.get("name"))

        # additional attribute: reference to the corresponding network
        self._profile_config = profile_config

    def create(self):
        super()._create(self._profile_config)


class Container(Resource):
    def __init__(self, container_config):
        # the container name is a concatenation of its type, the project name and the deployment stage
        super().__init__("/1.0/containers", container_config.get("name"))

        # additional attribute: reference to the project's profile
        self._container_config = container_config

    def create(self):
        super()._create(self._container_config)

    # returns whether this specific container is running or not...
    def is_running(self):
        # by checking its status in the metadata
        return self.exists() and session.get(self.get_full_element_url()).json().get("metadata").get(
            "status") == "Running"

    # starts this specific container
    def start(self):
        if not self.exists():
            raise Exception("container starting failed: container must exist")

        # only does something if the resource isn't already running (idempotence)
        if not self.is_running():
            print("starting", self._collection_url, self._name)
            session.put(self.get_full_element_url() + "/state", json={"action": "start"})
            if not self.is_running():
                raise Exception("container starting failed")

    # stops this specific container
    def stop(self):
        if not self.exists():
            raise Exception("container stopping failed: container must exist")

        # only does something if the resource is running (idempotence)
        if self.is_running():
            print("stopping", self._collection_url, self._name)
            session.put(self.get_full_element_url() + "/state", json={"action": "stop"})
            if self.is_running():
                raise Exception("container stopping failed")


def create():
    for network in config.get("networks"):
        Network(network).create()
    for profile in config.get("profiles"):
        Profile(profile).create()
    for container in config.get("containers"):
        Container(container).create()


def start():
    for container in config.get("containers"):
        Container(container).start()


def stop():
    for container in config.get("containers"):
        Container(container).stop()


def delete():
    for container in config.get("containers"):
        container = Container(container)
        container.stop()
        container.delete()
    for profile in config.get("profiles"):
        Profile(profile).delete()
    for network in config.get("networks"):
        Network(network).delete()


# this "hook" will be executed after each request to allow some generic treatment of the response
# see http://docs.python-requests.org/en/master/user/advanced/#event-hooks
def hook(response, **kwargs):
    json = response.json()
    type = json.get("type")

    if type == "error":
        raise Exception(json)

    # this will wait for lxd asynchronous operations to be finished
    # see https://github.com/lxc/lxd/blob/master/doc/rest-api.md#background-operation
    if type == "async":
        return session.get(api_url + json.get("operation") + "/wait")


if __name__ == '__main__':
    api_url = "http+unix://%2Fvar%2Flib%2Flxd%2Funix.socket"

    config = yaml.load(sys.stdin, Loader=yaml.BaseLoader)

    # opens a unix socket session for the rest of the script
    session = requests_unixsocket.Session()
    session.hooks['response'].append(hook)

    argparser = argparse.ArgumentParser()
    argparser.add_argument("command", choices=["create", "start", "stop", "delete"])
    args = argparser.parse_args()

    globals()[args.command]()

    session.close()
